# homelabctl completion helper functions

_homelabctl_complete_packages() {
  homelabctl -q setup list --names-only 2>/dev/null
}

_homelabctl_complete_categories() {
  homelabctl -q setup list --category-names 2>/dev/null
}

_homelabctl_complete_profiles() {
  homelabctl -q setup profile list --names-only 2>/dev/null
}

# Bash completion script for homelabctl
# Generated by radp-bash-framework

_homelabctl() {
    local cur prev words cword

    # 兼容模式：如果 _init_completion 不存在，使用手动初始化
    if type _init_completion &>/dev/null; then
        _init_completion || return
    else
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword="$COMP_CWORD"
    fi

    local i cmd_path=""

    # 构建当前命令路径
    for ((i = 1; i < cword; i++)); do
        case "${words[i]}" in
            -*) continue ;;
            *)
                if [[ -z "$cmd_path" ]]; then
                    cmd_path="${words[i]}"
                else
                    cmd_path="$cmd_path ${words[i]}"
                fi
                ;;
        esac
    done

    # Command completions
    case "$cmd_path" in
        '')
            COMPREPLY=($(compgen -W "completion info setup version vf  -q --quiet -v --verbose --debug --config --help --version" -- "$cur"))
            ;;
        'completion')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'setup')
            COMPREPLY=($(compgen -W "configure deps info install list profile  --help" -- "$cur"))
            ;;
        'setup configure')
            COMPREPLY=($(compgen -W "chrony expand-lvm gpg-import gpg-preset list yadm  --help" -- "$cur"))
            ;;
        'setup configure chrony')
            COMPREPLY=($(compgen -W "--help -s --servers -p --pool -t --timezone" -- "$cur"))
            ;;
        'setup configure expand-lvm')
            COMPREPLY=($(compgen -W "--help -p --partition -v --vg -l --lv" -- "$cur"))
            ;;
        'setup configure gpg-import')
            COMPREPLY=($(compgen -W "--help -p --public-key -p --public-key-file -s --secret-key-file -p --passphrase -p --passphrase-file -k --key-id -k --keyserver -t --trust-level -o --ownertrust-file -u --user" -- "$cur"))
            ;;
        'setup configure gpg-preset')
            COMPREPLY=($(compgen -W "--help -k --key-uid -p --passphrase -p --passphrase-file -u --user" -- "$cur"))
            ;;
        'setup configure list')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'setup configure yadm')
            COMPREPLY=($(compgen -W "--help -r --repo-url -c --class -h --https-user -h --https-token -h --https-token-file -s --ssh-key-file -s --ssh-host -s --ssh-port -u --user" -- "$cur"))
            ;;
        'setup deps')
            # 计算参数位置（减去命令路径深度）
            local arg_idx=0
            for ((i = 1; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;;
                    *) ((arg_idx++)) ;;
                esac
            done
            ((arg_idx -= 2)) || true
            # 根据参数位置补全
            case "$arg_idx" in
                0)
                    local completions
                    completions=$(_homelabctl_complete_packages 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help -r --reverse" -- "$cur"))
            ;;
        'setup info')
            # 计算参数位置（减去命令路径深度）
            local arg_idx=0
            for ((i = 1; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;;
                    *) ((arg_idx++)) ;;
                esac
            done
            ((arg_idx -= 2)) || true
            # 根据参数位置补全
            case "$arg_idx" in
                0)
                    local completions
                    completions=$(_homelabctl_complete_packages 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help -a --all-platforms" -- "$cur"))
            ;;
        'setup install')
            # 计算参数位置（减去命令路径深度）
            local arg_idx=0
            for ((i = 1; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;;
                    *) ((arg_idx++)) ;;
                esac
            done
            ((arg_idx -= 2)) || true
            # 根据参数位置补全
            case "$arg_idx" in
                0)
                    local completions
                    completions=$(_homelabctl_complete_packages 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help -v --version -d --dry-run -n --no-deps" -- "$cur"))
            ;;
        'setup list')
            case "$prev" in
                -c)
                    local completions
                    completions=$(_homelabctl_complete_categories 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
                --category)
                    local completions
                    completions=$(_homelabctl_complete_categories 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help -c --category -i --installed -c --categories -n --names-only -c --category-names" -- "$cur"))
            ;;
        'setup profile')
            COMPREPLY=($(compgen -W "apply list show  --help" -- "$cur"))
            ;;
        'setup profile apply')
            # 计算参数位置（减去命令路径深度）
            local arg_idx=0
            for ((i = 1; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;;
                    *) ((arg_idx++)) ;;
                esac
            done
            ((arg_idx -= 3)) || true
            # 根据参数位置补全
            case "$arg_idx" in
                0)
                    local completions
                    completions=$(_homelabctl_complete_profiles 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help -d --dry-run -c --continue -s --skip-installed -n --no-deps" -- "$cur"))
            ;;
        'setup profile list')
            COMPREPLY=($(compgen -W "--help -n --names-only" -- "$cur"))
            ;;
        'setup profile show')
            # 计算参数位置（减去命令路径深度）
            local arg_idx=0
            for ((i = 1; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;;
                    *) ((arg_idx++)) ;;
                esac
            done
            ((arg_idx -= 3)) || true
            # 根据参数位置补全
            case "$arg_idx" in
                0)
                    local completions
                    completions=$(_homelabctl_complete_profiles 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'version')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'info')
            COMPREPLY=($(compgen -W "--help -j --json" -- "$cur"))
            ;;
        'vf')
            # Delegate to radp-vf's native completion for consistent experience
            if type _radp_vf &>/dev/null; then
                # Shift words to simulate radp-vf being called directly
                local radp_vf_words=("radp-vf" "${words[@]:2}")
                local radp_vf_cword=$((cword - 1))
                COMP_WORDS=("${radp_vf_words[@]}")
                COMP_CWORD=$radp_vf_cword
                COMP_LINE="${radp_vf_words[*]}"
                COMP_POINT=${#COMP_LINE}
                _radp_vf
            else
                # Fallback if radp-vf completion not loaded
                local radp_vf_cmds="init vg list dump-config generate validate info template completion version help"
                COMPREPLY=($(compgen -W "$radp_vf_cmds" -- "$cur"))
            fi
            ;;
        vf\ *)
            # Delegate vf subcommands to radp-vf completion
            if type _radp_vf &>/dev/null; then
                local radp_vf_words=("radp-vf" "${words[@]:2}")
                local radp_vf_cword=$((cword - 1))
                COMP_WORDS=("${radp_vf_words[@]}")
                COMP_CWORD=$radp_vf_cword
                COMP_LINE="${radp_vf_words[*]}"
                COMP_POINT=${#COMP_LINE}
                _radp_vf
            else
                COMPREPLY=()
            fi
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _homelabctl homelabctl
