#compdef homelabctl

# Zsh completion script for homelabctl
# Generated by radp-bash-framework

_APP_NAME() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '1: :->command' \
        '*:: :->args'

    case "$state" in
        command)
            local commands=(
                'completion:Generate shell completion script'
                'version:Show homelabctl version information'
                'vf:Manage vf'
                'vg:Run vagrant commands (passthrough to vagrant)'
            )
            _describe 'command' commands
            ;;
        args)
            case "${words[1]}" in
                completion)
                    _arguments \
                        '(-h --help)'{-h,--help}'[Show help]' \
                        '*:file:_files'
                    ;;
                version)
                    _arguments \
                        '(-h --help)'{-h,--help}'[Show help]' \
                        '*:file:_files'
                    ;;
                vf)
                    local subcommands=(
                        'dump-config:Export merged configuration'
                        'generate:Generate standalone Vagrantfile'
                        'info:Show current environment information'
                        'init:Initialize a new radp-vagrant-framework project'
                        'list:List clusters and guests from configuration'
                        'validate:Validate YAML configuration files'
                        'version:Show radp-vagrant-framework version'
                    )
                    _describe 'subcommand' subcommands
                    ;;
                vg)
                    _arguments \
                        '(-h --help)'{-h,--help}'[Show help]' \
                        (-e --env)'{-e,--env}[Environment name]:name:' \
                        (-c --config)'{-c,--config}[Config directory path]:dir:' \
                        '*:file:_files'
                    ;;
                *)
                    _files
                    ;;
            esac
            ;;
    esac
}

_APP_NAME "$@"
