# Bash completion script for homelabctl
# Generated by radp-bash-framework with custom dynamic completions

# Dynamic completion helper functions
_homelabctl_setup_packages() {
    # Get package names from registry
    local registry_file="${HOMELABCTL_ROOT:-}/src/main/shell/libs/setup/registry.yaml"
    local user_registry="${HOME}/.config/homelabctl/setup/registry.yaml"

    local packages=""

    # Parse builtin registry
    if [[ -f "$registry_file" ]]; then
        packages=$(grep -E '^  [a-zA-Z0-9_-]+:$' "$registry_file" 2>/dev/null | sed 's/^  //' | sed 's/:$//' | tr '\n' ' ')
    fi

    # Parse user registry
    if [[ -f "$user_registry" ]]; then
        local user_packages
        user_packages=$(grep -E '^  [a-zA-Z0-9_-]+:$' "$user_registry" 2>/dev/null | sed 's/^  //' | sed 's/:$//' | tr '\n' ' ')
        packages="$packages $user_packages"
    fi

    echo "$packages"
}

_homelabctl_setup_profiles() {
    # Get profile names from profiles directories
    local builtin_dir="${HOMELABCTL_ROOT:-}/src/main/shell/libs/setup/profiles"
    local user_dir="${HOME}/.config/homelabctl/setup/profiles"

    local profiles=""

    # Builtin profiles
    if [[ -d "$builtin_dir" ]]; then
        for f in "$builtin_dir"/*.yaml; do
            [[ -f "$f" ]] && profiles="$profiles $(basename "$f" .yaml)"
        done
    fi

    # User profiles
    if [[ -d "$user_dir" ]]; then
        for f in "$user_dir"/*.yaml; do
            [[ -f "$f" ]] && profiles="$profiles $(basename "$f" .yaml)"
        done
    fi

    echo "$profiles"
}

_homelabctl_setup_categories() {
    # Get category names from registry
    local registry_file="${HOMELABCTL_ROOT:-}/src/main/shell/libs/setup/registry.yaml"

    if [[ -f "$registry_file" ]]; then
        # Extract categories section
        sed -n '/^categories:/,/^[^ ]/p' "$registry_file" 2>/dev/null | \
            grep -E '^  [a-zA-Z0-9_-]+:$' | sed 's/^  //' | sed 's/:$//' | tr '\n' ' '
    fi
}

_homelabctl() {
    local cur prev words cword

    # Compatibility mode: if _init_completion doesn't exist, use manual initialization
    if type _init_completion &>/dev/null; then
        _init_completion || return
    else
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword="$COMP_CWORD"
    fi

    local i cmd_path=""

    # Build current command path
    for ((i = 1; i < cword; i++)); do
        case "${words[i]}" in
            -*) continue ;;
            *)
                if [[ -z "$cmd_path" ]]; then
                    cmd_path="${words[i]}"
                else
                    cmd_path="$cmd_path ${words[i]}"
                fi
                ;;
        esac
    done

    # Handle dynamic completions based on previous word
    case "$prev" in
        # Package name completions
        install|info)
            if [[ "$cmd_path" == "setup install" || "$cmd_path" == "setup info" || "$cmd_path" == "setup" ]]; then
                COMPREPLY=($(compgen -W "$(_homelabctl_setup_packages)" -- "$cur"))
                return
            fi
            ;;
        # Profile name completions
        show|apply)
            if [[ "$cmd_path" == "setup profile show" || "$cmd_path" == "setup profile apply" || "$cmd_path" == "setup profile" ]]; then
                COMPREPLY=($(compgen -W "$(_homelabctl_setup_profiles)" -- "$cur"))
                return
            fi
            ;;
        # Category completions for -c/--category
        -c|--category)
            if [[ "$cmd_path" == setup* ]]; then
                COMPREPLY=($(compgen -W "$(_homelabctl_setup_categories)" -- "$cur"))
                return
            fi
            ;;
    esac

    # Command completions
    case "$cmd_path" in
        '')
            COMPREPLY=($(compgen -W "completion setup version vf vg --help --version" -- "$cur"))
            ;;
        'completion')
            COMPREPLY=($(compgen -W "bash zsh --help" -- "$cur"))
            ;;
        'setup')
            COMPREPLY=($(compgen -W "info install list profile --help" -- "$cur"))
            ;;
        'setup info')
            COMPREPLY=($(compgen -W "$(_homelabctl_setup_packages) --help" -- "$cur"))
            ;;
        'setup install')
            COMPREPLY=($(compgen -W "$(_homelabctl_setup_packages) --help -v --version --dry-run" -- "$cur"))
            ;;
        'setup list')
            COMPREPLY=($(compgen -W "--help -c --category --installed --categories" -- "$cur"))
            ;;
        'setup profile')
            COMPREPLY=($(compgen -W "apply list show --help" -- "$cur"))
            ;;
        'setup profile apply')
            COMPREPLY=($(compgen -W "$(_homelabctl_setup_profiles) --help --dry-run --continue --skip-installed" -- "$cur"))
            ;;
        'setup profile list')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'setup profile show')
            COMPREPLY=($(compgen -W "$(_homelabctl_setup_profiles) --help" -- "$cur"))
            ;;
        'version')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'vf')
            COMPREPLY=($(compgen -W "dump-config generate info init list template validate version --help" -- "$cur"))
            ;;
        'vf dump-config')
            COMPREPLY=($(compgen -W "--help -e --env -f --format -o --output" -- "$cur"))
            ;;
        'vf generate')
            COMPREPLY=($(compgen -W "--help -e --env" -- "$cur"))
            ;;
        'vf info')
            COMPREPLY=($(compgen -W "--help -e --env -j --json" -- "$cur"))
            ;;
        'vf init')
            COMPREPLY=($(compgen -W "--help -t --template --set" -- "$cur"))
            ;;
        'vf list')
            COMPREPLY=($(compgen -W "--help -e --env -v --verbose -p --provisions -s --synced-folders -t --triggers" -- "$cur"))
            ;;
        'vf template')
            COMPREPLY=($(compgen -W "list show --help" -- "$cur"))
            ;;
        'vf template list')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'vf template show')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'vf validate')
            COMPREPLY=($(compgen -W "--help -e --env" -- "$cur"))
            ;;
        'vf version')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'vg')
            COMPREPLY=($(compgen -W "--help -e --env -c --config" -- "$cur"))
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _homelabctl homelabctl
