# homelabctl completion helper functions

_homelabctl_complete_packages() {
    homelabctl setup list --names-only 2>/dev/null
}

_homelabctl_complete_categories() {
    homelabctl setup list --category-names 2>/dev/null
}

_homelabctl_complete_profiles() {
    homelabctl setup profile list --names-only 2>/dev/null
}

#compdef homelabctl

# Zsh completion script for homelabctl
# Generated by radp-bash-framework

_homelabctl() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '1: :->command' \
        '*:: :->args'

    case "$state" in
        command)
            local commands=(
                'completion:Generate shell completion script'
                'setup:Manage setup'
                'version:Show homelabctl version information'
                'vf:Manage vf'
                'vg:Run vagrant commands (passthrough to vagrant)'
            )
            _describe 'command' commands
            ;;
        args)
            case "${words[1]}" in
                completion)
                    _arguments \
                        '(-h --help)'{-h,--help}'[Show help]' \
                        '1:shell:_files' \

                    ;;
                setup)
                    local subcommands=(
                        'info:Show package details'
                        'install:Install a software package'
                        'list:List available packages'
                        'profile:Manage profile'
                    )
                    case "${words[2]}" in
                    info)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            '1:name:->arg_name' \


                        case "$state" in
                            arg_name)
                                local completions
                                completions=($(_homelabctl_complete_packages 2>/dev/null))
                                _describe 'name' completions
                                ;;
                        esac
                        ;;
                    install)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            (-v --version)'{-v,--version}[Specific version (default: latest)]:ver:' \
                            (-d --dry-run)'{-d,--dry-run}[Show what would be installed without installing]' \
                            '1:name:->arg_name' \


                        case "$state" in
                            arg_name)
                                local completions
                                completions=($(_homelabctl_complete_packages 2>/dev/null))
                                _describe 'name' completions
                                ;;
                        esac
                        ;;
                    list)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            (-c --category)'{-c,--category}[Filter by category]:name:->opt_category' \
                            (-i --installed)'{-i,--installed}[Show only installed packages]' \
                            (-c --categories)'{-c,--categories}[List available categories]' \
                            (-n --names-only)'{-n,--names-only}[Output package names only (for completion)]' \
                            (-c --category-names)'{-c,--category-names}[Output category names only (for completion)]' \
                            '*:file:_files'

                        case "$state" in
                            opt_category)
                                local completions
                                completions=($(_homelabctl_complete_categories 2>/dev/null))
                                _describe 'name' completions
                                ;;
                        esac
                        ;;
                    profile)
                        local subcommands=(
                            'apply:Apply a setup profile (install multiple packages)'
                            'list:List available setup profiles'
                            'show:Show profile details'
                        )
                        case "${words[3]}" in
                        apply)
                            _arguments \
                                '(-h --help)'{-h,--help}'[Show help]' \
                                (-d --dry-run)'{-d,--dry-run}[Show what would be installed]' \
                                (-c --continue)'{-c,--continue}[Continue on error]' \
                                (-s --skip-installed)'{-s,--skip-installed}[Skip already installed packages]' \
                                '1:name:->arg_name' \


                            case "$state" in
                                arg_name)
                                    local completions
                                    completions=($(_homelabctl_complete_profiles 2>/dev/null))
                                    _describe 'name' completions
                                    ;;
                            esac
                            ;;
                        list)
                            _arguments \
                                '(-h --help)'{-h,--help}'[Show help]' \
                                (-n --names-only)'{-n,--names-only}[Output profile names only (for completion)]' \
                                '*:file:_files'
                            ;;
                        show)
                            _arguments \
                                '(-h --help)'{-h,--help}'[Show help]' \
                                '1:name:->arg_name' \


                            case "$state" in
                                arg_name)
                                    local completions
                                    completions=($(_homelabctl_complete_profiles 2>/dev/null))
                                    _describe 'name' completions
                                    ;;
                            esac
                            ;;
                            *)
                                _describe 'subcommand' subcommands
                                ;;
                        esac
                        ;;
                        *)
                            _describe 'subcommand' subcommands
                            ;;
                    esac
                    ;;
                version)
                    _arguments \
                        '(-h --help)'{-h,--help}'[Show help]' \
                        '*:file:_files'
                    ;;
                vf)
                    local subcommands=(
                        'dump-config:Export merged configuration'
                        'generate:Generate standalone Vagrantfile'
                        'info:Show current environment information'
                        'init:Initialize a new radp-vagrant-framework project'
                        'list:List clusters and guests from configuration'
                        'template:Manage template'
                        'validate:Validate YAML configuration files'
                        'version:Show radp-vagrant-framework version'
                    )
                    case "${words[2]}" in
                    dump-config)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            (-e --env)'{-e,--env}[Override environment name]:name:' \
                            (-f --format)'{-f,--format}[Output format (json or yaml, default: json)]:format:' \
                            (-o --output)'{-o,--output}[Output file path]:file:' \
                            '1:filter:_files' \

                        ;;
                    generate)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            (-e --env)'{-e,--env}[Override environment name]:name:' \
                            '1:output:_files' \

                        ;;
                    info)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            (-e --env)'{-e,--env}[Environment name]:name:' \
                            (-j --json)'{-j,--json}[Output as JSON]' \
                            '*:file:_files'
                        ;;
                    init)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            (-t --template)'{-t,--template}[Use a template (default: base)]:name:' \
                            (-s --set)'{-s,--set}[]:var:' \
                            '1:dir:_files' \

                        ;;
                    list)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            (-e --env)'{-e,--env}[Override environment name]:name:' \
                            (-v --verbose)'{-v,--verbose}[Show detailed info (box, network, provisions, etc.)]' \
                            (-p --provisions)'{-p,--provisions}[Show provisions only]' \
                            (-s --synced-folders)'{-s,--synced-folders}[Show synced folders only]' \
                            (-t --triggers)'{-t,--triggers}[Show triggers only]' \
                            '1:filter:_files' \

                        ;;
                    template)
                        local subcommands=(
                            'list:List available project templates'
                            'show:Show template details and variables'
                        )
                        case "${words[3]}" in
                        list)
                            _arguments \
                                '(-h --help)'{-h,--help}'[Show help]' \
                                '*:file:_files'
                            ;;
                        show)
                            _arguments \
                                '(-h --help)'{-h,--help}'[Show help]' \
                                '1:name:_files' \

                            ;;
                            *)
                                _describe 'subcommand' subcommands
                                ;;
                        esac
                        ;;
                    validate)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            (-e --env)'{-e,--env}[Override environment name]:name:' \
                            '*:file:_files'
                        ;;
                    version)
                        _arguments \
                            '(-h --help)'{-h,--help}'[Show help]' \
                            '*:file:_files'
                        ;;
                        *)
                            _describe 'subcommand' subcommands
                            ;;
                    esac
                    ;;
                vg)
                    _arguments \
                        '(-h --help)'{-h,--help}'[Show help]' \
                        (-e --env)'{-e,--env}[Environment name]:name:' \
                        (-c --config)'{-c,--config}[Config directory path]:dir:' \
                        '1:cmd:_files' \
                        '*:args~:_files' \

                    ;;
                *)
                    _files
                    ;;
            esac
            ;;
    esac
}

_homelabctl "$@"
