# homelabctl completion helper functions

_homelabctl_complete_packages() {
    homelabctl setup list --names-only 2>/dev/null
}

_homelabctl_complete_categories() {
    homelabctl setup list --category-names 2>/dev/null
}

_homelabctl_complete_profiles() {
    homelabctl setup profile list --names-only 2>/dev/null
}

# Bash completion script for homelabctl
# Generated by radp-bash-framework

_homelabctl() {
    local cur prev words cword

    # 兼容模式：如果 _init_completion 不存在，使用手动初始化
    if type _init_completion &>/dev/null; then
        _init_completion || return
    else
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword="$COMP_CWORD"
    fi

    local i cmd_path=""

    # 构建当前命令路径
    for ((i = 1; i < cword; i++)); do
        case "${words[i]}" in
            -*) continue ;;
            *)
                if [[ -z "$cmd_path" ]]; then
                    cmd_path="${words[i]}"
                else
                    cmd_path="$cmd_path ${words[i]}"
                fi
                ;;
        esac
    done

    # Command completions
    case "$cmd_path" in
        '')
            COMPREPLY=($(compgen -W "completion setup version vf vg  --help --version" -- "$cur"))
            ;;
        'completion')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'setup')
            COMPREPLY=($(compgen -W "info install list profile  --help" -- "$cur"))
            ;;
        'setup info')
            case "$prev" in
                *)
            esac
            # 计算参数位置
            local arg_idx=0
            for ((i = 1; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;;
                    *) ((arg_idx++)) ;;
                esac
            done
            # 根据参数位置补全
            case "$arg_idx" in
                0)
                    local completions
                    completions=$(_homelabctl_complete_packages 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'setup install')
            case "$prev" in
                *)
                    # 检查是否是需要值的选项
                    ;;
            esac
            # 计算参数位置
            local arg_idx=0
            for ((i = 1; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;;
                    *) ((arg_idx++)) ;;
                esac
            done
            # 根据参数位置补全
            case "$arg_idx" in
                0)
                    local completions
                    completions=$(_homelabctl_complete_packages 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help -v --version -d --dry-run" -- "$cur"))
            ;;
        'setup list')
            case "$prev" in
                -c)
                    local completions
                    completions=$(_homelabctl_complete_categories 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
                --category)
                    local completions
                    completions=$(_homelabctl_complete_categories 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
                *)
                    # 检查是否是需要值的选项
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help -c --category -i --installed -c --categories -n --names-only -c --category-names" -- "$cur"))
            ;;
        'setup profile')
            COMPREPLY=($(compgen -W "apply list show  --help" -- "$cur"))
            ;;
        'setup profile apply')
            case "$prev" in
                *)
            esac
            # 计算参数位置
            local arg_idx=0
            for ((i = 1; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;;
                    *) ((arg_idx++)) ;;
                esac
            done
            # 根据参数位置补全
            case "$arg_idx" in
                0)
                    local completions
                    completions=$(_homelabctl_complete_profiles 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help -d --dry-run -c --continue -s --skip-installed" -- "$cur"))
            ;;
        'setup profile list')
            COMPREPLY=($(compgen -W "--help -n --names-only" -- "$cur"))
            ;;
        'setup profile show')
            case "$prev" in
                *)
            esac
            # 计算参数位置
            local arg_idx=0
            for ((i = 1; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;;
                    *) ((arg_idx++)) ;;
                esac
            done
            # 根据参数位置补全
            case "$arg_idx" in
                0)
                    local completions
                    completions=$(_homelabctl_complete_profiles 2>/dev/null)
                    COMPREPLY=($(compgen -W "$completions" -- "$cur"))
                    return
                    ;;
            esac
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'version')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'vf')
            COMPREPLY=($(compgen -W "dump-config generate info init list template validate version  --help" -- "$cur"))
            ;;
        'vf dump-config')
            COMPREPLY=($(compgen -W "--help -e --env -f --format -o --output" -- "$cur"))
            ;;
        'vf generate')
            COMPREPLY=($(compgen -W "--help -e --env" -- "$cur"))
            ;;
        'vf info')
            COMPREPLY=($(compgen -W "--help -e --env -j --json" -- "$cur"))
            ;;
        'vf init')
            COMPREPLY=($(compgen -W "--help -t --template -s --set" -- "$cur"))
            ;;
        'vf list')
            COMPREPLY=($(compgen -W "--help -e --env -v --verbose -p --provisions -s --synced-folders -t --triggers" -- "$cur"))
            ;;
        'vf template')
            COMPREPLY=($(compgen -W "list show  --help" -- "$cur"))
            ;;
        'vf template list')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'vf template show')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'vf validate')
            COMPREPLY=($(compgen -W "--help -e --env" -- "$cur"))
            ;;
        'vf version')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'vg')
            COMPREPLY=($(compgen -W "--help -e --env -c --config" -- "$cur"))
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _homelabctl homelabctl
